// Regenerate installed dependency inventories/notices. Does not modify dependencies.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root=process.cwd();
const packages=new Map(), texts=new Map();
function notice(file) {
  const content=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n');
  const id=crypto.createHash('sha256').update(content).digest('hex');
  texts.set(id,content);return id;
}
function licenseFiles(dir,depth=0) {
  if(depth>2)return [];
  return fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry=>{
    const file=path.join(dir,entry.name);
    if(entry.isSymbolicLink())return [];
    if(entry.isFile()&&/^(licen[cs]e|copying|notice|copyright)([._-]|$)/i.test(entry.name))return [file];
    if(entry.isDirectory()&&/^(licenses?|third.party.licenses?)$/i.test(entry.name))return licenseFiles(file,depth+1);
    return [];
  });
}
for(const entry of fs.readdirSync('node_modules/.pnpm')) {
  const nm=path.join('node_modules/.pnpm',entry,'node_modules');
  if(!fs.existsSync(nm))continue;
  for(const name of fs.readdirSync(nm)) {
    const candidates=name.startsWith('@')?fs.readdirSync(path.join(nm,name)).map(n=>path.join(nm,name,n)):[path.join(nm,name)];
    for(const dir of candidates) {
      if(fs.lstatSync(dir).isSymbolicLink()||!fs.existsSync(path.join(dir,'package.json')))continue;
      const pkg=JSON.parse(fs.readFileSync(path.join(dir,'package.json'),'utf8'));
      const key=`npm:${pkg.name}@${pkg.version}`;
      const declared=pkg.license??pkg.licenses??'NOT DECLARED';
      packages.set(key,{ecosystem:'npm',name:pkg.name,version:pkg.version,license:declared,notices:licenseFiles(dir).map(notice)});
    }
  }
}
const python=process.env.LUCASCAD_PYTHON??path.join(root,process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');
const pythonCode=`import importlib.metadata as m,json
out=[]
for d in m.distributions():
 meta=d.metadata
 classifiers=[v for v in meta.get_all('Classifier',[]) if v.startswith('License ::')]
 license=meta.get('License-Expression') or meta.get('License') or '; '.join(classifiers) or 'NOT DECLARED'
 files=[str(d.locate_file(f)) for f in d.files or [] if str(f).replace(chr(92),'/').split('/')[-1].lower().startswith(('license','licence','copying','notice','copyright')) or ('.dist-info/' in str(f).replace(chr(92),'/') and '/licenses/' in str(f).replace(chr(92),'/'))]
 out.append(dict(ecosystem='python',name=meta['Name'],version=d.version,license=license,files=files))
print(json.dumps(out))`;
for(const pkg of JSON.parse(execFileSync(python,['-c',pythonCode],{encoding:'utf8',maxBuffer:8*1024*1024}))) {
  const {files,...data}=pkg;
  packages.set(`python:${pkg.name}@${pkg.version}`,{...data,notices:files.filter(f=>fs.existsSync(f)&&fs.statSync(f).isFile()).map(notice)});
}
const inventory=[...packages.values()].sort((a,b)=>`${a.ecosystem}:${a.name}@${a.version}`.localeCompare(`${b.ecosystem}:${b.name}@${b.version}`));
fs.mkdirSync('docs/release',{recursive:true});
fs.writeFileSync('docs/release/dependencies.json',JSON.stringify({scope:'Installed Windows development environment; includes transitive/build/test packages. Not a complete cross-platform binary BOM. Regenerate on every release target.',packages:inventory},null,2)+'\n');
let output='THIRD-PARTY LICENSE TEXTS\n\nGenerated by node tools/release_audit.mjs from installed packages.\nThese texts retain upstream ownership; LucasCad does not relicense them.\nSee THIRD_PARTY_NOTICES.md for scope and binary redistribution limitations.\n\n';
for(const [id,content] of [...texts].sort(([a],[b])=>a.localeCompare(b))) {
  const owners=inventory.filter(p=>p.notices.includes(id)).map(p=>`${p.ecosystem}:${p.name}@${p.version}`).join(', ');
  output+=`\n${'='.repeat(72)}\n${owners}\nSHA256: ${id}\n${'='.repeat(72)}\n${content}\n`;
}
fs.writeFileSync('THIRD_PARTY_LICENSES.txt',output);
console.log(JSON.stringify({npm:inventory.filter(p=>p.ecosystem==='npm').length,python:inventory.filter(p=>p.ecosystem==='python').length,uniqueNoticeTexts:texts.size,missingNoticeFiles:inventory.filter(p=>!p.notices.length).map(p=>`${p.ecosystem}:${p.name}@${p.version}`)},null,2));
